name: CI

on:
  push:
    branches:
      - main
      - development
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install additional dependencies
        run: npm install globals --save-dev

      - name: Install additional dependencies
        run: npm install eslint-plugin-jest --save-dev

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t gestor .

      - name: Run ESLint
        run: npm run lint

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test
